### ISSUE TITLE
inotifywait: command not found

### ISSUE THREAD

**Issue by probonopd** [RazZziel/PortableLinuxGames#1]
```
me@host:~$  Downloads/monitorAppImages.sh 
Watching /home/me/Applications/...
Added /home/me/Applications//*.run...
Downloads/monitorAppImages.sh: line 60: inotifywait: command not found
```

`sudo apt-get install inotify-tools` resolved this for me. It would be nice if this would be made into an AppImage, let's eat our own dogfood :-)

```
me@host:~$  Downloads/monitorAppImages.sh 
Watching /home/me/Applications/...
Added /home/me/Applications//*.run...
Setting up watches.  Beware: since -r was given, this may take a while!
Couldn't watch /home/me/Applications/: No such file or directory
```

Wouldn't it be nice if this was automatically set up for the user? Also, `*.run` should not be assumed to be the filename extension for AppImages. It should be `.AppImage` or just nothing.

**Comment by probonopd** [comment]
Besides, it seems not to make the AppImage executable or do anything to it...

```
me@host:~$  Downloads/monitorAppImages.sh 
Watching /home/me/Applications/...
Added /home/me/Applications//*.run...
Setting up watches.  Beware: since -r was given, this may take a while!
Watches established.
Added /home/me/Applications//*.run...
Removed /home/me/Applications//*.run...
Added /home/me/Applications//*.run...
```

**Comment by RazZziel** [comment]
> It would be nice if this would be made into an AppImage, let's eat our own dogfood :-)

It could be packaged along with the script, or the script could be implemented it in C again to avoid the dependency. Packaged along with the script seems like a good idea, specially because I'd like to stop using `--icon` to exctact the icon, as it causes havoc on old AppImages that don't understand the `--icon` parameter and execute the game full-screen instead, thus `xorriso` is needed. Provided you have `xorriso` compiled for several platforms on your repo, I'll move it there, inside a proper AppDir.

> `Couldn't watch /home/me/Applications/: No such file or directory`
> Wouldn't it be nice if this was automatically set up for the user?

Hmmm, it could be. Not completely sure if it'd be better to ignore the directory if it doesn't exist, instead of _forcing_ the directory down the user's throat, though. Maybe it'd be better to inform the user that the directory doesn't exist, and let him either chose his apps directory or create a new directory, with `zenity --file-selection` for instance.

> Also, *.run should not be assumed to be the filename extension for AppImages. It should be .AppImage or just nothing.

I had to drop `.AppImage` for `.run` years ago, because IIRC:
- Google Chrome used to automatically change the extension of all `.AppImage` files I tried to download to `.bin`
- I **think** some versions of Nautilus refused to run executable files if they didn't have a `.run` (they instead poped up the "Open this file with..." dialog)
- It was the most standard and recognizable extension for a simple runnable file
- If we need to tell between an AppImage and another runnable file, we can rely on the `file -k` command kind of introspection

Removing the extension doesn't seem right; every file you download on the Internet is expected to have an extension, regardless of the tradition in Linux for commands inside `/usr/bin` and suchlike (and Chrome used to append the .bin).

Anyway, I'll modify the script to scan both for .run and for .AppImage files, verifying they exist. Also subdirectories must be scanned.

> Besides, it seems not to make the AppImage executable or do anything to it...

In that log there doesn't seem to be any `.run` file to process. The script right now doesn't make the file executable (which is a good idea btw, WIP).

**Comment by probonopd** [comment]
> I'd like to stop using --icon to exctact the icon, as it causes havoc on old AppImages that don't understand the --icon parameter

Why don't we introduce a `--version` or something like that?

> Google Chrome used to automatically change the extension of all .AppImage files I tried to download to .bin

I cannot reproduce this, at least with recent versions

**Comment by RazZziel** [comment]
> Why don't we introduce a `--version` or something like that?

Same problem, all the AppImages that currently don't support that argument will run the application instead of printing the AppImage version and quit.

Besides, both `--icon` and `--version` can collide with the embedded app's own parameters. Something like `APPIMAGE_COMMAND="version" ./AppImage` would be safer.

Either way, I'd rather avoid running any AppImage with any parameters at all, it's too risky (more or less like the famous [ldd vulnerability](http://www.catonmat.net/blog/ldd-arbitrary-code-execution/)). Either the AppImage itself runs whatever it needs to run transparently to the user on a normal run (i.e. creating icon and menu entries in background, if they don't exist, automatically every time the AppImage is run); or/and that's handled by an external script that inspects the AppImage without running it (with `xorriso` or whatever).

> I cannot reproduce this, at least with recent versions

Yep, neither can I right now, it was a thing of the Chrome versions that existed when I made that decision

**Comment by RazZziel** [comment]
I moved the script to https://github.com/probonopd/AppImageKit/tree/master/AppImageMonitor.AppDir

Right now I have two unmet binary dependencies:
- http://cgit.freedesktop.org/xdg/desktop-file-utils/tree/src/update-desktop-database.c
- https://github.com/rvoicilas/inotify-tools/blob/master/src/inotifywait.c

Should we import the binaries from some old distro, like with xorriso (which Ubuntu was it taken from?), or should we create git submodules inside the repo, in order to fetch the code from the original repo and build the binaries with the same compiler that builds AppRun?

**Comment by probonopd** [comment]
I guess that using git submodules and building all of these binary dependencies [properly](https://github.com/probonopd/AppImageKit/tree/master/LibcWrapGenerator) ourselves is the way to go. Not only for the new binary dependencies but also for the old ones. Gives us more platform independence too.

**Comment by RazZziel** [comment]
Instead of using git submodules, I'm letting CMake download the dependencies itself, it's pretty neat: https://clbin.com/EgzMJ (WIP)

**Comment by RazZziel** [comment]
Moving discussion to https://github.com/probonopd/AppImageKit/issues/33
